    name: Weekly Pipeline Update

    on:
      schedule:
        # This cron expression runs the workflow every monday day at 14:00 UTC (10am Eastern)
        - cron: '0 14 * * 1' 

    jobs:
      update-pipeline:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.x'
          - name: Install dependencies
            run: pip install -r requirements.txt
          - name: Run update pipeline script
            # run: python update_pipeline.py
            run:  |
              echo Running File...
              status=$(python update_pipeline.py >> logs/log.txt 2>&1; echo $?)
              cat logs/log.txt
              echo ::set-output name=status::$status
          - name: Commit log
            run: |
              git config --global user.name 'GitHub Action'
              git config --global user.email 'action@github.com'
              git add -A
              git checkout master
              git diff-index --quiet HEAD || git commit -am "deploy workflow logs"
              git push
